# Makefile.in generated by automake 1.15 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2014 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/cpuminer-opt
pkgincludedir = $(includedir)/cpuminer-opt
pkglibdir = $(libdir)/cpuminer-opt
pkglibexecdir = $(libexecdir)/cpuminer-opt
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-pc-linux-gnu
target_triplet = x86_64-pc-linux-gnu
bin_PROGRAMS = cpuminer$(EXEEXT)
am__append_1 = asm/neoscrypt_asm.S
#am__append_2 = asm/sha2-x86.S asm/scrypt-x86.S asm/aesb-x86.S
am__append_3 = asm/sha2-x64.S asm/scrypt-x64.S asm/aesb-x64.S
#am__append_4 = asm/sha2-arm.S asm/scrypt-arm.S
#am__append_5 = -DNOASM
#am__append_6 = compat/winansi.c
#am__append_7 = -Wl,--stack,10485760
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = cpuminer-config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"
PROGRAMS = $(bin_PROGRAMS)
am__cpuminer_SOURCES_DIST = cpu-miner.c util.c uint256.cpp api.c \
	sysinfos.c algo-gate-api.c algo/blake/sph_blake.c \
	algo/sha3/sph_sha2.c algo/sha3/sph_sha2big.c crypto/blake2s.c \
	crypto/aesb.c algo/blake/blake.c algo/blake/blake2.c \
	algo/lyra2/lyra2.c algo/lyra2/sponge.c algo/lyra2/zcoin.c \
	algo/sha2/sha2.c asm/neoscrypt_asm.S asm/sha2-x86.S \
	asm/scrypt-x86.S asm/aesb-x86.S asm/sha2-x64.S \
	asm/scrypt-x64.S asm/aesb-x64.S asm/sha2-arm.S \
	asm/scrypt-arm.S compat/winansi.c
am__dirstamp = $(am__leading_dot)dirstamp
am__objects_1 = asm/cpuminer-neoscrypt_asm.$(OBJEXT)
#am__objects_2 =  \
#	asm/cpuminer-sha2-x86.$(OBJEXT) \
#	asm/cpuminer-scrypt-x86.$(OBJEXT) \
#	asm/cpuminer-aesb-x86.$(OBJEXT)
am__objects_3 = asm/cpuminer-sha2-x64.$(OBJEXT) \
	asm/cpuminer-scrypt-x64.$(OBJEXT) \
	asm/cpuminer-aesb-x64.$(OBJEXT)
#am__objects_4 =  \
#	asm/cpuminer-sha2-arm.$(OBJEXT) \
#	asm/cpuminer-scrypt-arm.$(OBJEXT)
#am__objects_5 = compat/cpuminer-winansi.$(OBJEXT)
am_cpuminer_OBJECTS = cpuminer-cpu-miner.$(OBJEXT) \
	cpuminer-util.$(OBJEXT) cpuminer-uint256.$(OBJEXT) \
	cpuminer-api.$(OBJEXT) cpuminer-sysinfos.$(OBJEXT) \
	cpuminer-algo-gate-api.$(OBJEXT) \
	algo/blake/cpuminer-sph_blake.$(OBJEXT) \
	algo/sha3/cpuminer-sph_sha2.$(OBJEXT) \
	algo/sha3/cpuminer-sph_sha2big.$(OBJEXT) \
	crypto/cpuminer-blake2s.$(OBJEXT) \
	crypto/cpuminer-aesb.$(OBJEXT) \
	algo/blake/cpuminer-blake.$(OBJEXT) \
	algo/blake/cpuminer-blake2.$(OBJEXT) \
	algo/lyra2/cpuminer-lyra2.$(OBJEXT) \
	algo/lyra2/cpuminer-sponge.$(OBJEXT) \
	algo/lyra2/cpuminer-zcoin.$(OBJEXT) \
	algo/sha2/cpuminer-sha2.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_3) $(am__objects_4) \
	$(am__objects_5)
cpuminer_OBJECTS = $(am_cpuminer_OBJECTS)
cpuminer_DEPENDENCIES =
cpuminer_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(cpuminer_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
CPPASCOMPILE = $(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS)
AM_V_CPPAS = $(am__v_CPPAS_$(V))
am__v_CPPAS_ = $(am__v_CPPAS_$(AM_DEFAULT_VERBOSITY))
am__v_CPPAS_0 = @echo "  CPPAS   " $@;
am__v_CPPAS_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(cpuminer_SOURCES)
DIST_SOURCES = $(am__cpuminer_SOURCES_DIST)
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
man1dir = $(mandir)/man1
NROFF = nroff
MANS = $(dist_man_MANS)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)cpuminer-config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
DIST_SUBDIRS = $(SUBDIRS)
am__DIST_COMMON = $(dist_man_MANS) $(srcdir)/Makefile.in \
	$(srcdir)/cpuminer-config.h.in AUTHORS COPYING ChangeLog \
	compile config.guess config.sub depcomp install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/ubuntu/cpuminer-zcoin/missing aclocal-1.15
ALLOCA = 
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /home/ubuntu/cpuminer-zcoin/missing autoconf
AUTOHEADER = ${SHELL} /home/ubuntu/cpuminer-zcoin/missing autoheader
AUTOMAKE = ${SHELL} /home/ubuntu/cpuminer-zcoin/missing automake-1.15
AWK = gawk
CC = gcc
CCAS = gcc
CCASDEPMODE = depmode=gcc3
CCASFLAGS = -O3 -march=native -Wall
CCDEPMODE = depmode=gcc3
CFLAGS = -O3 -march=native -Wall  -Iyes/include
CPP = gcc -E
CPPFLAGS =   -Iyes/include
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -O3 -march=native -Wall -std=gnu++11
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
JANSSON_LIBS = -ljansson
LDFLAGS =   -Lyes/lib 
LIBCURL = -lcurl -lz
LIBCURL_CFLAGS =  -Iyes/include
LIBCURL_CPPFLAGS =  -Iyes/include
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAINT = #
MAKEINFO = ${SHELL} /home/ubuntu/cpuminer-zcoin/missing makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = cpuminer-opt
PACKAGE_BUGREPORT = 
PACKAGE_NAME = cpuminer-opt
PACKAGE_STRING = cpuminer-opt 3.5.0
PACKAGE_TARNAME = cpuminer-opt
PACKAGE_URL = 
PACKAGE_VERSION = 3.5.0
PATH_SEPARATOR = :
PTHREAD_FLAGS = 
PTHREAD_LIBS = -lpthread
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 3.5.0
WS2_LIBS = 
abs_builddir = /home/ubuntu/cpuminer-zcoin
abs_srcdir = /home/ubuntu/cpuminer-zcoin
abs_top_builddir = /home/ubuntu/cpuminer-zcoin
abs_top_srcdir = /home/ubuntu/cpuminer-zcoin
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-pc-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/ubuntu/cpuminer-zcoin/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target = x86_64-pc-linux-gnu
target_alias = 
target_cpu = x86_64
target_os = linux-gnu
target_vendor = pc
top_build_prefix = 
top_builddir = .
top_srcdir = .
JANSSON_INCLUDES = 
#JANSSON_INCLUDES = -I$(top_srcdir)/compat/jansson
EXTRA_DIST = example-cfg.json nomacro.pl
SUBDIRS = compat
ALL_INCLUDES =  -fno-strict-aliasing $(JANSSON_INCLUDES) -I.
dist_man_MANS = cpuminer.1
cpuminer_SOURCES = cpu-miner.c util.c uint256.cpp api.c sysinfos.c \
	algo-gate-api.c algo/blake/sph_blake.c algo/sha3/sph_sha2.c \
	algo/sha3/sph_sha2big.c crypto/blake2s.c crypto/aesb.c \
	algo/blake/blake.c algo/blake/blake2.c algo/lyra2/lyra2.c \
	algo/lyra2/sponge.c algo/lyra2/zcoin.c algo/sha2/sha2.c \
	$(am__append_1) $(am__append_2) $(am__append_3) \
	$(am__append_4) $(am__append_6)
disable_flags = $(am__append_5)
cpuminer_LDFLAGS =   -Lyes/lib 
cpuminer_LDADD = -lcurl -lz -ljansson -lpthread  -lssl -lcrypto -lgmp
cpuminer_CPPFLAGS =  -Iyes/include $(ALL_INCLUDES)
cpuminer_CFLAGS = -Wno-pointer-sign -Wno-pointer-to-int-cast \
	$(disable_flags) $(am__append_7)

# use to profile an object
# gprof_cflags = -pg -g3
# cpuminer_LDFLAGS += -pg
# cpuminer_CFLAGS += -fno-inline-functions -static

# copy/paste from generated Makefile
#common_ccflags = $(DEFS) $(ALL_INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS)
all: cpuminer-config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .S .c .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in: # $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure: # $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4): # $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

cpuminer-config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/cpuminer-config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status cpuminer-config.h
$(srcdir)/cpuminer-config.h.in: # $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f cpuminer-config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
algo/blake/$(am__dirstamp):
	@$(MKDIR_P) algo/blake
	@: > algo/blake/$(am__dirstamp)
algo/blake/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) algo/blake/$(DEPDIR)
	@: > algo/blake/$(DEPDIR)/$(am__dirstamp)
algo/blake/cpuminer-sph_blake.$(OBJEXT): algo/blake/$(am__dirstamp) \
	algo/blake/$(DEPDIR)/$(am__dirstamp)
algo/sha3/$(am__dirstamp):
	@$(MKDIR_P) algo/sha3
	@: > algo/sha3/$(am__dirstamp)
algo/sha3/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) algo/sha3/$(DEPDIR)
	@: > algo/sha3/$(DEPDIR)/$(am__dirstamp)
algo/sha3/cpuminer-sph_sha2.$(OBJEXT): algo/sha3/$(am__dirstamp) \
	algo/sha3/$(DEPDIR)/$(am__dirstamp)
algo/sha3/cpuminer-sph_sha2big.$(OBJEXT): algo/sha3/$(am__dirstamp) \
	algo/sha3/$(DEPDIR)/$(am__dirstamp)
crypto/$(am__dirstamp):
	@$(MKDIR_P) crypto
	@: > crypto/$(am__dirstamp)
crypto/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) crypto/$(DEPDIR)
	@: > crypto/$(DEPDIR)/$(am__dirstamp)
crypto/cpuminer-blake2s.$(OBJEXT): crypto/$(am__dirstamp) \
	crypto/$(DEPDIR)/$(am__dirstamp)
crypto/cpuminer-aesb.$(OBJEXT): crypto/$(am__dirstamp) \
	crypto/$(DEPDIR)/$(am__dirstamp)
algo/blake/cpuminer-blake.$(OBJEXT): algo/blake/$(am__dirstamp) \
	algo/blake/$(DEPDIR)/$(am__dirstamp)
algo/blake/cpuminer-blake2.$(OBJEXT): algo/blake/$(am__dirstamp) \
	algo/blake/$(DEPDIR)/$(am__dirstamp)
algo/lyra2/$(am__dirstamp):
	@$(MKDIR_P) algo/lyra2
	@: > algo/lyra2/$(am__dirstamp)
algo/lyra2/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) algo/lyra2/$(DEPDIR)
	@: > algo/lyra2/$(DEPDIR)/$(am__dirstamp)
algo/lyra2/cpuminer-lyra2.$(OBJEXT): algo/lyra2/$(am__dirstamp) \
	algo/lyra2/$(DEPDIR)/$(am__dirstamp)
algo/lyra2/cpuminer-sponge.$(OBJEXT): algo/lyra2/$(am__dirstamp) \
	algo/lyra2/$(DEPDIR)/$(am__dirstamp)
algo/lyra2/cpuminer-zcoin.$(OBJEXT): algo/lyra2/$(am__dirstamp) \
	algo/lyra2/$(DEPDIR)/$(am__dirstamp)
algo/sha2/$(am__dirstamp):
	@$(MKDIR_P) algo/sha2
	@: > algo/sha2/$(am__dirstamp)
algo/sha2/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) algo/sha2/$(DEPDIR)
	@: > algo/sha2/$(DEPDIR)/$(am__dirstamp)
algo/sha2/cpuminer-sha2.$(OBJEXT): algo/sha2/$(am__dirstamp) \
	algo/sha2/$(DEPDIR)/$(am__dirstamp)
asm/$(am__dirstamp):
	@$(MKDIR_P) asm
	@: > asm/$(am__dirstamp)
asm/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) asm/$(DEPDIR)
	@: > asm/$(DEPDIR)/$(am__dirstamp)
asm/cpuminer-neoscrypt_asm.$(OBJEXT): asm/$(am__dirstamp) \
	asm/$(DEPDIR)/$(am__dirstamp)
asm/cpuminer-sha2-x86.$(OBJEXT): asm/$(am__dirstamp) \
	asm/$(DEPDIR)/$(am__dirstamp)
asm/cpuminer-scrypt-x86.$(OBJEXT): asm/$(am__dirstamp) \
	asm/$(DEPDIR)/$(am__dirstamp)
asm/cpuminer-aesb-x86.$(OBJEXT): asm/$(am__dirstamp) \
	asm/$(DEPDIR)/$(am__dirstamp)
asm/cpuminer-sha2-x64.$(OBJEXT): asm/$(am__dirstamp) \
	asm/$(DEPDIR)/$(am__dirstamp)
asm/cpuminer-scrypt-x64.$(OBJEXT): asm/$(am__dirstamp) \
	asm/$(DEPDIR)/$(am__dirstamp)
asm/cpuminer-aesb-x64.$(OBJEXT): asm/$(am__dirstamp) \
	asm/$(DEPDIR)/$(am__dirstamp)
asm/cpuminer-sha2-arm.$(OBJEXT): asm/$(am__dirstamp) \
	asm/$(DEPDIR)/$(am__dirstamp)
asm/cpuminer-scrypt-arm.$(OBJEXT): asm/$(am__dirstamp) \
	asm/$(DEPDIR)/$(am__dirstamp)
compat/$(am__dirstamp):
	@$(MKDIR_P) compat
	@: > compat/$(am__dirstamp)
compat/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) compat/$(DEPDIR)
	@: > compat/$(DEPDIR)/$(am__dirstamp)
compat/cpuminer-winansi.$(OBJEXT): compat/$(am__dirstamp) \
	compat/$(DEPDIR)/$(am__dirstamp)

cpuminer$(EXEEXT): $(cpuminer_OBJECTS) $(cpuminer_DEPENDENCIES) $(EXTRA_cpuminer_DEPENDENCIES) 
	@rm -f cpuminer$(EXEEXT)
	$(AM_V_CXXLD)$(cpuminer_LINK) $(cpuminer_OBJECTS) $(cpuminer_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f algo/blake/*.$(OBJEXT)
	-rm -f algo/lyra2/*.$(OBJEXT)
	-rm -f algo/sha2/*.$(OBJEXT)
	-rm -f algo/sha3/*.$(OBJEXT)
	-rm -f asm/*.$(OBJEXT)
	-rm -f compat/*.$(OBJEXT)
	-rm -f crypto/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/cpuminer-algo-gate-api.Po
include ./$(DEPDIR)/cpuminer-api.Po
include ./$(DEPDIR)/cpuminer-cpu-miner.Po
include ./$(DEPDIR)/cpuminer-sysinfos.Po
include ./$(DEPDIR)/cpuminer-uint256.Po
include ./$(DEPDIR)/cpuminer-util.Po
include algo/blake/$(DEPDIR)/cpuminer-blake.Po
include algo/blake/$(DEPDIR)/cpuminer-blake2.Po
include algo/blake/$(DEPDIR)/cpuminer-sph_blake.Po
include algo/lyra2/$(DEPDIR)/cpuminer-lyra2.Po
include algo/lyra2/$(DEPDIR)/cpuminer-sponge.Po
include algo/lyra2/$(DEPDIR)/cpuminer-zcoin.Po
include algo/sha2/$(DEPDIR)/cpuminer-sha2.Po
include algo/sha3/$(DEPDIR)/cpuminer-sph_sha2.Po
include algo/sha3/$(DEPDIR)/cpuminer-sph_sha2big.Po
include asm/$(DEPDIR)/cpuminer-aesb-x64.Po
include asm/$(DEPDIR)/cpuminer-aesb-x86.Po
include asm/$(DEPDIR)/cpuminer-neoscrypt_asm.Po
include asm/$(DEPDIR)/cpuminer-scrypt-arm.Po
include asm/$(DEPDIR)/cpuminer-scrypt-x64.Po
include asm/$(DEPDIR)/cpuminer-scrypt-x86.Po
include asm/$(DEPDIR)/cpuminer-sha2-arm.Po
include asm/$(DEPDIR)/cpuminer-sha2-x64.Po
include asm/$(DEPDIR)/cpuminer-sha2-x86.Po
include compat/$(DEPDIR)/cpuminer-winansi.Po
include crypto/$(DEPDIR)/cpuminer-aesb.Po
include crypto/$(DEPDIR)/cpuminer-blake2s.Po

.S.o:
	$(AM_V_CPPAS)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CPPASCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CPPAS)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CPPASCOMPILE) -c -o $@ $<

.S.obj:
	$(AM_V_CPPAS)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CPPASCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CPPAS)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CPPASCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

asm/cpuminer-neoscrypt_asm.o: asm/neoscrypt_asm.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-neoscrypt_asm.o -MD -MP -MF asm/$(DEPDIR)/cpuminer-neoscrypt_asm.Tpo -c -o asm/cpuminer-neoscrypt_asm.o `test -f 'asm/neoscrypt_asm.S' || echo '$(srcdir)/'`asm/neoscrypt_asm.S
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-neoscrypt_asm.Tpo asm/$(DEPDIR)/cpuminer-neoscrypt_asm.Po
#	$(AM_V_CPPAS)source='asm/neoscrypt_asm.S' object='asm/cpuminer-neoscrypt_asm.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-neoscrypt_asm.o `test -f 'asm/neoscrypt_asm.S' || echo '$(srcdir)/'`asm/neoscrypt_asm.S

asm/cpuminer-neoscrypt_asm.obj: asm/neoscrypt_asm.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-neoscrypt_asm.obj -MD -MP -MF asm/$(DEPDIR)/cpuminer-neoscrypt_asm.Tpo -c -o asm/cpuminer-neoscrypt_asm.obj `if test -f 'asm/neoscrypt_asm.S'; then $(CYGPATH_W) 'asm/neoscrypt_asm.S'; else $(CYGPATH_W) '$(srcdir)/asm/neoscrypt_asm.S'; fi`
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-neoscrypt_asm.Tpo asm/$(DEPDIR)/cpuminer-neoscrypt_asm.Po
#	$(AM_V_CPPAS)source='asm/neoscrypt_asm.S' object='asm/cpuminer-neoscrypt_asm.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-neoscrypt_asm.obj `if test -f 'asm/neoscrypt_asm.S'; then $(CYGPATH_W) 'asm/neoscrypt_asm.S'; else $(CYGPATH_W) '$(srcdir)/asm/neoscrypt_asm.S'; fi`

asm/cpuminer-sha2-x86.o: asm/sha2-x86.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-sha2-x86.o -MD -MP -MF asm/$(DEPDIR)/cpuminer-sha2-x86.Tpo -c -o asm/cpuminer-sha2-x86.o `test -f 'asm/sha2-x86.S' || echo '$(srcdir)/'`asm/sha2-x86.S
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-sha2-x86.Tpo asm/$(DEPDIR)/cpuminer-sha2-x86.Po
#	$(AM_V_CPPAS)source='asm/sha2-x86.S' object='asm/cpuminer-sha2-x86.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-sha2-x86.o `test -f 'asm/sha2-x86.S' || echo '$(srcdir)/'`asm/sha2-x86.S

asm/cpuminer-sha2-x86.obj: asm/sha2-x86.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-sha2-x86.obj -MD -MP -MF asm/$(DEPDIR)/cpuminer-sha2-x86.Tpo -c -o asm/cpuminer-sha2-x86.obj `if test -f 'asm/sha2-x86.S'; then $(CYGPATH_W) 'asm/sha2-x86.S'; else $(CYGPATH_W) '$(srcdir)/asm/sha2-x86.S'; fi`
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-sha2-x86.Tpo asm/$(DEPDIR)/cpuminer-sha2-x86.Po
#	$(AM_V_CPPAS)source='asm/sha2-x86.S' object='asm/cpuminer-sha2-x86.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-sha2-x86.obj `if test -f 'asm/sha2-x86.S'; then $(CYGPATH_W) 'asm/sha2-x86.S'; else $(CYGPATH_W) '$(srcdir)/asm/sha2-x86.S'; fi`

asm/cpuminer-scrypt-x86.o: asm/scrypt-x86.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-scrypt-x86.o -MD -MP -MF asm/$(DEPDIR)/cpuminer-scrypt-x86.Tpo -c -o asm/cpuminer-scrypt-x86.o `test -f 'asm/scrypt-x86.S' || echo '$(srcdir)/'`asm/scrypt-x86.S
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-scrypt-x86.Tpo asm/$(DEPDIR)/cpuminer-scrypt-x86.Po
#	$(AM_V_CPPAS)source='asm/scrypt-x86.S' object='asm/cpuminer-scrypt-x86.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-scrypt-x86.o `test -f 'asm/scrypt-x86.S' || echo '$(srcdir)/'`asm/scrypt-x86.S

asm/cpuminer-scrypt-x86.obj: asm/scrypt-x86.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-scrypt-x86.obj -MD -MP -MF asm/$(DEPDIR)/cpuminer-scrypt-x86.Tpo -c -o asm/cpuminer-scrypt-x86.obj `if test -f 'asm/scrypt-x86.S'; then $(CYGPATH_W) 'asm/scrypt-x86.S'; else $(CYGPATH_W) '$(srcdir)/asm/scrypt-x86.S'; fi`
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-scrypt-x86.Tpo asm/$(DEPDIR)/cpuminer-scrypt-x86.Po
#	$(AM_V_CPPAS)source='asm/scrypt-x86.S' object='asm/cpuminer-scrypt-x86.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-scrypt-x86.obj `if test -f 'asm/scrypt-x86.S'; then $(CYGPATH_W) 'asm/scrypt-x86.S'; else $(CYGPATH_W) '$(srcdir)/asm/scrypt-x86.S'; fi`

asm/cpuminer-aesb-x86.o: asm/aesb-x86.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-aesb-x86.o -MD -MP -MF asm/$(DEPDIR)/cpuminer-aesb-x86.Tpo -c -o asm/cpuminer-aesb-x86.o `test -f 'asm/aesb-x86.S' || echo '$(srcdir)/'`asm/aesb-x86.S
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-aesb-x86.Tpo asm/$(DEPDIR)/cpuminer-aesb-x86.Po
#	$(AM_V_CPPAS)source='asm/aesb-x86.S' object='asm/cpuminer-aesb-x86.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-aesb-x86.o `test -f 'asm/aesb-x86.S' || echo '$(srcdir)/'`asm/aesb-x86.S

asm/cpuminer-aesb-x86.obj: asm/aesb-x86.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-aesb-x86.obj -MD -MP -MF asm/$(DEPDIR)/cpuminer-aesb-x86.Tpo -c -o asm/cpuminer-aesb-x86.obj `if test -f 'asm/aesb-x86.S'; then $(CYGPATH_W) 'asm/aesb-x86.S'; else $(CYGPATH_W) '$(srcdir)/asm/aesb-x86.S'; fi`
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-aesb-x86.Tpo asm/$(DEPDIR)/cpuminer-aesb-x86.Po
#	$(AM_V_CPPAS)source='asm/aesb-x86.S' object='asm/cpuminer-aesb-x86.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-aesb-x86.obj `if test -f 'asm/aesb-x86.S'; then $(CYGPATH_W) 'asm/aesb-x86.S'; else $(CYGPATH_W) '$(srcdir)/asm/aesb-x86.S'; fi`

asm/cpuminer-sha2-x64.o: asm/sha2-x64.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-sha2-x64.o -MD -MP -MF asm/$(DEPDIR)/cpuminer-sha2-x64.Tpo -c -o asm/cpuminer-sha2-x64.o `test -f 'asm/sha2-x64.S' || echo '$(srcdir)/'`asm/sha2-x64.S
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-sha2-x64.Tpo asm/$(DEPDIR)/cpuminer-sha2-x64.Po
#	$(AM_V_CPPAS)source='asm/sha2-x64.S' object='asm/cpuminer-sha2-x64.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-sha2-x64.o `test -f 'asm/sha2-x64.S' || echo '$(srcdir)/'`asm/sha2-x64.S

asm/cpuminer-sha2-x64.obj: asm/sha2-x64.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-sha2-x64.obj -MD -MP -MF asm/$(DEPDIR)/cpuminer-sha2-x64.Tpo -c -o asm/cpuminer-sha2-x64.obj `if test -f 'asm/sha2-x64.S'; then $(CYGPATH_W) 'asm/sha2-x64.S'; else $(CYGPATH_W) '$(srcdir)/asm/sha2-x64.S'; fi`
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-sha2-x64.Tpo asm/$(DEPDIR)/cpuminer-sha2-x64.Po
#	$(AM_V_CPPAS)source='asm/sha2-x64.S' object='asm/cpuminer-sha2-x64.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-sha2-x64.obj `if test -f 'asm/sha2-x64.S'; then $(CYGPATH_W) 'asm/sha2-x64.S'; else $(CYGPATH_W) '$(srcdir)/asm/sha2-x64.S'; fi`

asm/cpuminer-scrypt-x64.o: asm/scrypt-x64.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-scrypt-x64.o -MD -MP -MF asm/$(DEPDIR)/cpuminer-scrypt-x64.Tpo -c -o asm/cpuminer-scrypt-x64.o `test -f 'asm/scrypt-x64.S' || echo '$(srcdir)/'`asm/scrypt-x64.S
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-scrypt-x64.Tpo asm/$(DEPDIR)/cpuminer-scrypt-x64.Po
#	$(AM_V_CPPAS)source='asm/scrypt-x64.S' object='asm/cpuminer-scrypt-x64.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-scrypt-x64.o `test -f 'asm/scrypt-x64.S' || echo '$(srcdir)/'`asm/scrypt-x64.S

asm/cpuminer-scrypt-x64.obj: asm/scrypt-x64.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-scrypt-x64.obj -MD -MP -MF asm/$(DEPDIR)/cpuminer-scrypt-x64.Tpo -c -o asm/cpuminer-scrypt-x64.obj `if test -f 'asm/scrypt-x64.S'; then $(CYGPATH_W) 'asm/scrypt-x64.S'; else $(CYGPATH_W) '$(srcdir)/asm/scrypt-x64.S'; fi`
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-scrypt-x64.Tpo asm/$(DEPDIR)/cpuminer-scrypt-x64.Po
#	$(AM_V_CPPAS)source='asm/scrypt-x64.S' object='asm/cpuminer-scrypt-x64.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-scrypt-x64.obj `if test -f 'asm/scrypt-x64.S'; then $(CYGPATH_W) 'asm/scrypt-x64.S'; else $(CYGPATH_W) '$(srcdir)/asm/scrypt-x64.S'; fi`

asm/cpuminer-aesb-x64.o: asm/aesb-x64.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-aesb-x64.o -MD -MP -MF asm/$(DEPDIR)/cpuminer-aesb-x64.Tpo -c -o asm/cpuminer-aesb-x64.o `test -f 'asm/aesb-x64.S' || echo '$(srcdir)/'`asm/aesb-x64.S
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-aesb-x64.Tpo asm/$(DEPDIR)/cpuminer-aesb-x64.Po
#	$(AM_V_CPPAS)source='asm/aesb-x64.S' object='asm/cpuminer-aesb-x64.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-aesb-x64.o `test -f 'asm/aesb-x64.S' || echo '$(srcdir)/'`asm/aesb-x64.S

asm/cpuminer-aesb-x64.obj: asm/aesb-x64.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-aesb-x64.obj -MD -MP -MF asm/$(DEPDIR)/cpuminer-aesb-x64.Tpo -c -o asm/cpuminer-aesb-x64.obj `if test -f 'asm/aesb-x64.S'; then $(CYGPATH_W) 'asm/aesb-x64.S'; else $(CYGPATH_W) '$(srcdir)/asm/aesb-x64.S'; fi`
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-aesb-x64.Tpo asm/$(DEPDIR)/cpuminer-aesb-x64.Po
#	$(AM_V_CPPAS)source='asm/aesb-x64.S' object='asm/cpuminer-aesb-x64.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-aesb-x64.obj `if test -f 'asm/aesb-x64.S'; then $(CYGPATH_W) 'asm/aesb-x64.S'; else $(CYGPATH_W) '$(srcdir)/asm/aesb-x64.S'; fi`

asm/cpuminer-sha2-arm.o: asm/sha2-arm.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-sha2-arm.o -MD -MP -MF asm/$(DEPDIR)/cpuminer-sha2-arm.Tpo -c -o asm/cpuminer-sha2-arm.o `test -f 'asm/sha2-arm.S' || echo '$(srcdir)/'`asm/sha2-arm.S
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-sha2-arm.Tpo asm/$(DEPDIR)/cpuminer-sha2-arm.Po
#	$(AM_V_CPPAS)source='asm/sha2-arm.S' object='asm/cpuminer-sha2-arm.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-sha2-arm.o `test -f 'asm/sha2-arm.S' || echo '$(srcdir)/'`asm/sha2-arm.S

asm/cpuminer-sha2-arm.obj: asm/sha2-arm.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-sha2-arm.obj -MD -MP -MF asm/$(DEPDIR)/cpuminer-sha2-arm.Tpo -c -o asm/cpuminer-sha2-arm.obj `if test -f 'asm/sha2-arm.S'; then $(CYGPATH_W) 'asm/sha2-arm.S'; else $(CYGPATH_W) '$(srcdir)/asm/sha2-arm.S'; fi`
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-sha2-arm.Tpo asm/$(DEPDIR)/cpuminer-sha2-arm.Po
#	$(AM_V_CPPAS)source='asm/sha2-arm.S' object='asm/cpuminer-sha2-arm.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-sha2-arm.obj `if test -f 'asm/sha2-arm.S'; then $(CYGPATH_W) 'asm/sha2-arm.S'; else $(CYGPATH_W) '$(srcdir)/asm/sha2-arm.S'; fi`

asm/cpuminer-scrypt-arm.o: asm/scrypt-arm.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-scrypt-arm.o -MD -MP -MF asm/$(DEPDIR)/cpuminer-scrypt-arm.Tpo -c -o asm/cpuminer-scrypt-arm.o `test -f 'asm/scrypt-arm.S' || echo '$(srcdir)/'`asm/scrypt-arm.S
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-scrypt-arm.Tpo asm/$(DEPDIR)/cpuminer-scrypt-arm.Po
#	$(AM_V_CPPAS)source='asm/scrypt-arm.S' object='asm/cpuminer-scrypt-arm.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-scrypt-arm.o `test -f 'asm/scrypt-arm.S' || echo '$(srcdir)/'`asm/scrypt-arm.S

asm/cpuminer-scrypt-arm.obj: asm/scrypt-arm.S
	$(AM_V_CPPAS)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT asm/cpuminer-scrypt-arm.obj -MD -MP -MF asm/$(DEPDIR)/cpuminer-scrypt-arm.Tpo -c -o asm/cpuminer-scrypt-arm.obj `if test -f 'asm/scrypt-arm.S'; then $(CYGPATH_W) 'asm/scrypt-arm.S'; else $(CYGPATH_W) '$(srcdir)/asm/scrypt-arm.S'; fi`
	$(AM_V_at)$(am__mv) asm/$(DEPDIR)/cpuminer-scrypt-arm.Tpo asm/$(DEPDIR)/cpuminer-scrypt-arm.Po
#	$(AM_V_CPPAS)source='asm/scrypt-arm.S' object='asm/cpuminer-scrypt-arm.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o asm/cpuminer-scrypt-arm.obj `if test -f 'asm/scrypt-arm.S'; then $(CYGPATH_W) 'asm/scrypt-arm.S'; else $(CYGPATH_W) '$(srcdir)/asm/scrypt-arm.S'; fi`

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

cpuminer-cpu-miner.o: cpu-miner.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT cpuminer-cpu-miner.o -MD -MP -MF $(DEPDIR)/cpuminer-cpu-miner.Tpo -c -o cpuminer-cpu-miner.o `test -f 'cpu-miner.c' || echo '$(srcdir)/'`cpu-miner.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/cpuminer-cpu-miner.Tpo $(DEPDIR)/cpuminer-cpu-miner.Po
#	$(AM_V_CC)source='cpu-miner.c' object='cpuminer-cpu-miner.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o cpuminer-cpu-miner.o `test -f 'cpu-miner.c' || echo '$(srcdir)/'`cpu-miner.c

cpuminer-cpu-miner.obj: cpu-miner.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT cpuminer-cpu-miner.obj -MD -MP -MF $(DEPDIR)/cpuminer-cpu-miner.Tpo -c -o cpuminer-cpu-miner.obj `if test -f 'cpu-miner.c'; then $(CYGPATH_W) 'cpu-miner.c'; else $(CYGPATH_W) '$(srcdir)/cpu-miner.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/cpuminer-cpu-miner.Tpo $(DEPDIR)/cpuminer-cpu-miner.Po
#	$(AM_V_CC)source='cpu-miner.c' object='cpuminer-cpu-miner.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o cpuminer-cpu-miner.obj `if test -f 'cpu-miner.c'; then $(CYGPATH_W) 'cpu-miner.c'; else $(CYGPATH_W) '$(srcdir)/cpu-miner.c'; fi`

cpuminer-util.o: util.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT cpuminer-util.o -MD -MP -MF $(DEPDIR)/cpuminer-util.Tpo -c -o cpuminer-util.o `test -f 'util.c' || echo '$(srcdir)/'`util.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/cpuminer-util.Tpo $(DEPDIR)/cpuminer-util.Po
#	$(AM_V_CC)source='util.c' object='cpuminer-util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o cpuminer-util.o `test -f 'util.c' || echo '$(srcdir)/'`util.c

cpuminer-util.obj: util.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT cpuminer-util.obj -MD -MP -MF $(DEPDIR)/cpuminer-util.Tpo -c -o cpuminer-util.obj `if test -f 'util.c'; then $(CYGPATH_W) 'util.c'; else $(CYGPATH_W) '$(srcdir)/util.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/cpuminer-util.Tpo $(DEPDIR)/cpuminer-util.Po
#	$(AM_V_CC)source='util.c' object='cpuminer-util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o cpuminer-util.obj `if test -f 'util.c'; then $(CYGPATH_W) 'util.c'; else $(CYGPATH_W) '$(srcdir)/util.c'; fi`

cpuminer-api.o: api.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT cpuminer-api.o -MD -MP -MF $(DEPDIR)/cpuminer-api.Tpo -c -o cpuminer-api.o `test -f 'api.c' || echo '$(srcdir)/'`api.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/cpuminer-api.Tpo $(DEPDIR)/cpuminer-api.Po
#	$(AM_V_CC)source='api.c' object='cpuminer-api.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o cpuminer-api.o `test -f 'api.c' || echo '$(srcdir)/'`api.c

cpuminer-api.obj: api.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT cpuminer-api.obj -MD -MP -MF $(DEPDIR)/cpuminer-api.Tpo -c -o cpuminer-api.obj `if test -f 'api.c'; then $(CYGPATH_W) 'api.c'; else $(CYGPATH_W) '$(srcdir)/api.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/cpuminer-api.Tpo $(DEPDIR)/cpuminer-api.Po
#	$(AM_V_CC)source='api.c' object='cpuminer-api.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o cpuminer-api.obj `if test -f 'api.c'; then $(CYGPATH_W) 'api.c'; else $(CYGPATH_W) '$(srcdir)/api.c'; fi`

cpuminer-sysinfos.o: sysinfos.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT cpuminer-sysinfos.o -MD -MP -MF $(DEPDIR)/cpuminer-sysinfos.Tpo -c -o cpuminer-sysinfos.o `test -f 'sysinfos.c' || echo '$(srcdir)/'`sysinfos.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/cpuminer-sysinfos.Tpo $(DEPDIR)/cpuminer-sysinfos.Po
#	$(AM_V_CC)source='sysinfos.c' object='cpuminer-sysinfos.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o cpuminer-sysinfos.o `test -f 'sysinfos.c' || echo '$(srcdir)/'`sysinfos.c

cpuminer-sysinfos.obj: sysinfos.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT cpuminer-sysinfos.obj -MD -MP -MF $(DEPDIR)/cpuminer-sysinfos.Tpo -c -o cpuminer-sysinfos.obj `if test -f 'sysinfos.c'; then $(CYGPATH_W) 'sysinfos.c'; else $(CYGPATH_W) '$(srcdir)/sysinfos.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/cpuminer-sysinfos.Tpo $(DEPDIR)/cpuminer-sysinfos.Po
#	$(AM_V_CC)source='sysinfos.c' object='cpuminer-sysinfos.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o cpuminer-sysinfos.obj `if test -f 'sysinfos.c'; then $(CYGPATH_W) 'sysinfos.c'; else $(CYGPATH_W) '$(srcdir)/sysinfos.c'; fi`

cpuminer-algo-gate-api.o: algo-gate-api.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT cpuminer-algo-gate-api.o -MD -MP -MF $(DEPDIR)/cpuminer-algo-gate-api.Tpo -c -o cpuminer-algo-gate-api.o `test -f 'algo-gate-api.c' || echo '$(srcdir)/'`algo-gate-api.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/cpuminer-algo-gate-api.Tpo $(DEPDIR)/cpuminer-algo-gate-api.Po
#	$(AM_V_CC)source='algo-gate-api.c' object='cpuminer-algo-gate-api.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o cpuminer-algo-gate-api.o `test -f 'algo-gate-api.c' || echo '$(srcdir)/'`algo-gate-api.c

cpuminer-algo-gate-api.obj: algo-gate-api.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT cpuminer-algo-gate-api.obj -MD -MP -MF $(DEPDIR)/cpuminer-algo-gate-api.Tpo -c -o cpuminer-algo-gate-api.obj `if test -f 'algo-gate-api.c'; then $(CYGPATH_W) 'algo-gate-api.c'; else $(CYGPATH_W) '$(srcdir)/algo-gate-api.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/cpuminer-algo-gate-api.Tpo $(DEPDIR)/cpuminer-algo-gate-api.Po
#	$(AM_V_CC)source='algo-gate-api.c' object='cpuminer-algo-gate-api.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o cpuminer-algo-gate-api.obj `if test -f 'algo-gate-api.c'; then $(CYGPATH_W) 'algo-gate-api.c'; else $(CYGPATH_W) '$(srcdir)/algo-gate-api.c'; fi`

algo/blake/cpuminer-sph_blake.o: algo/blake/sph_blake.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/blake/cpuminer-sph_blake.o -MD -MP -MF algo/blake/$(DEPDIR)/cpuminer-sph_blake.Tpo -c -o algo/blake/cpuminer-sph_blake.o `test -f 'algo/blake/sph_blake.c' || echo '$(srcdir)/'`algo/blake/sph_blake.c
	$(AM_V_at)$(am__mv) algo/blake/$(DEPDIR)/cpuminer-sph_blake.Tpo algo/blake/$(DEPDIR)/cpuminer-sph_blake.Po
#	$(AM_V_CC)source='algo/blake/sph_blake.c' object='algo/blake/cpuminer-sph_blake.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/blake/cpuminer-sph_blake.o `test -f 'algo/blake/sph_blake.c' || echo '$(srcdir)/'`algo/blake/sph_blake.c

algo/blake/cpuminer-sph_blake.obj: algo/blake/sph_blake.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/blake/cpuminer-sph_blake.obj -MD -MP -MF algo/blake/$(DEPDIR)/cpuminer-sph_blake.Tpo -c -o algo/blake/cpuminer-sph_blake.obj `if test -f 'algo/blake/sph_blake.c'; then $(CYGPATH_W) 'algo/blake/sph_blake.c'; else $(CYGPATH_W) '$(srcdir)/algo/blake/sph_blake.c'; fi`
	$(AM_V_at)$(am__mv) algo/blake/$(DEPDIR)/cpuminer-sph_blake.Tpo algo/blake/$(DEPDIR)/cpuminer-sph_blake.Po
#	$(AM_V_CC)source='algo/blake/sph_blake.c' object='algo/blake/cpuminer-sph_blake.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/blake/cpuminer-sph_blake.obj `if test -f 'algo/blake/sph_blake.c'; then $(CYGPATH_W) 'algo/blake/sph_blake.c'; else $(CYGPATH_W) '$(srcdir)/algo/blake/sph_blake.c'; fi`

algo/sha3/cpuminer-sph_sha2.o: algo/sha3/sph_sha2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/sha3/cpuminer-sph_sha2.o -MD -MP -MF algo/sha3/$(DEPDIR)/cpuminer-sph_sha2.Tpo -c -o algo/sha3/cpuminer-sph_sha2.o `test -f 'algo/sha3/sph_sha2.c' || echo '$(srcdir)/'`algo/sha3/sph_sha2.c
	$(AM_V_at)$(am__mv) algo/sha3/$(DEPDIR)/cpuminer-sph_sha2.Tpo algo/sha3/$(DEPDIR)/cpuminer-sph_sha2.Po
#	$(AM_V_CC)source='algo/sha3/sph_sha2.c' object='algo/sha3/cpuminer-sph_sha2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/sha3/cpuminer-sph_sha2.o `test -f 'algo/sha3/sph_sha2.c' || echo '$(srcdir)/'`algo/sha3/sph_sha2.c

algo/sha3/cpuminer-sph_sha2.obj: algo/sha3/sph_sha2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/sha3/cpuminer-sph_sha2.obj -MD -MP -MF algo/sha3/$(DEPDIR)/cpuminer-sph_sha2.Tpo -c -o algo/sha3/cpuminer-sph_sha2.obj `if test -f 'algo/sha3/sph_sha2.c'; then $(CYGPATH_W) 'algo/sha3/sph_sha2.c'; else $(CYGPATH_W) '$(srcdir)/algo/sha3/sph_sha2.c'; fi`
	$(AM_V_at)$(am__mv) algo/sha3/$(DEPDIR)/cpuminer-sph_sha2.Tpo algo/sha3/$(DEPDIR)/cpuminer-sph_sha2.Po
#	$(AM_V_CC)source='algo/sha3/sph_sha2.c' object='algo/sha3/cpuminer-sph_sha2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/sha3/cpuminer-sph_sha2.obj `if test -f 'algo/sha3/sph_sha2.c'; then $(CYGPATH_W) 'algo/sha3/sph_sha2.c'; else $(CYGPATH_W) '$(srcdir)/algo/sha3/sph_sha2.c'; fi`

algo/sha3/cpuminer-sph_sha2big.o: algo/sha3/sph_sha2big.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/sha3/cpuminer-sph_sha2big.o -MD -MP -MF algo/sha3/$(DEPDIR)/cpuminer-sph_sha2big.Tpo -c -o algo/sha3/cpuminer-sph_sha2big.o `test -f 'algo/sha3/sph_sha2big.c' || echo '$(srcdir)/'`algo/sha3/sph_sha2big.c
	$(AM_V_at)$(am__mv) algo/sha3/$(DEPDIR)/cpuminer-sph_sha2big.Tpo algo/sha3/$(DEPDIR)/cpuminer-sph_sha2big.Po
#	$(AM_V_CC)source='algo/sha3/sph_sha2big.c' object='algo/sha3/cpuminer-sph_sha2big.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/sha3/cpuminer-sph_sha2big.o `test -f 'algo/sha3/sph_sha2big.c' || echo '$(srcdir)/'`algo/sha3/sph_sha2big.c

algo/sha3/cpuminer-sph_sha2big.obj: algo/sha3/sph_sha2big.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/sha3/cpuminer-sph_sha2big.obj -MD -MP -MF algo/sha3/$(DEPDIR)/cpuminer-sph_sha2big.Tpo -c -o algo/sha3/cpuminer-sph_sha2big.obj `if test -f 'algo/sha3/sph_sha2big.c'; then $(CYGPATH_W) 'algo/sha3/sph_sha2big.c'; else $(CYGPATH_W) '$(srcdir)/algo/sha3/sph_sha2big.c'; fi`
	$(AM_V_at)$(am__mv) algo/sha3/$(DEPDIR)/cpuminer-sph_sha2big.Tpo algo/sha3/$(DEPDIR)/cpuminer-sph_sha2big.Po
#	$(AM_V_CC)source='algo/sha3/sph_sha2big.c' object='algo/sha3/cpuminer-sph_sha2big.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/sha3/cpuminer-sph_sha2big.obj `if test -f 'algo/sha3/sph_sha2big.c'; then $(CYGPATH_W) 'algo/sha3/sph_sha2big.c'; else $(CYGPATH_W) '$(srcdir)/algo/sha3/sph_sha2big.c'; fi`

crypto/cpuminer-blake2s.o: crypto/blake2s.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT crypto/cpuminer-blake2s.o -MD -MP -MF crypto/$(DEPDIR)/cpuminer-blake2s.Tpo -c -o crypto/cpuminer-blake2s.o `test -f 'crypto/blake2s.c' || echo '$(srcdir)/'`crypto/blake2s.c
	$(AM_V_at)$(am__mv) crypto/$(DEPDIR)/cpuminer-blake2s.Tpo crypto/$(DEPDIR)/cpuminer-blake2s.Po
#	$(AM_V_CC)source='crypto/blake2s.c' object='crypto/cpuminer-blake2s.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o crypto/cpuminer-blake2s.o `test -f 'crypto/blake2s.c' || echo '$(srcdir)/'`crypto/blake2s.c

crypto/cpuminer-blake2s.obj: crypto/blake2s.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT crypto/cpuminer-blake2s.obj -MD -MP -MF crypto/$(DEPDIR)/cpuminer-blake2s.Tpo -c -o crypto/cpuminer-blake2s.obj `if test -f 'crypto/blake2s.c'; then $(CYGPATH_W) 'crypto/blake2s.c'; else $(CYGPATH_W) '$(srcdir)/crypto/blake2s.c'; fi`
	$(AM_V_at)$(am__mv) crypto/$(DEPDIR)/cpuminer-blake2s.Tpo crypto/$(DEPDIR)/cpuminer-blake2s.Po
#	$(AM_V_CC)source='crypto/blake2s.c' object='crypto/cpuminer-blake2s.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o crypto/cpuminer-blake2s.obj `if test -f 'crypto/blake2s.c'; then $(CYGPATH_W) 'crypto/blake2s.c'; else $(CYGPATH_W) '$(srcdir)/crypto/blake2s.c'; fi`

crypto/cpuminer-aesb.o: crypto/aesb.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT crypto/cpuminer-aesb.o -MD -MP -MF crypto/$(DEPDIR)/cpuminer-aesb.Tpo -c -o crypto/cpuminer-aesb.o `test -f 'crypto/aesb.c' || echo '$(srcdir)/'`crypto/aesb.c
	$(AM_V_at)$(am__mv) crypto/$(DEPDIR)/cpuminer-aesb.Tpo crypto/$(DEPDIR)/cpuminer-aesb.Po
#	$(AM_V_CC)source='crypto/aesb.c' object='crypto/cpuminer-aesb.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o crypto/cpuminer-aesb.o `test -f 'crypto/aesb.c' || echo '$(srcdir)/'`crypto/aesb.c

crypto/cpuminer-aesb.obj: crypto/aesb.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT crypto/cpuminer-aesb.obj -MD -MP -MF crypto/$(DEPDIR)/cpuminer-aesb.Tpo -c -o crypto/cpuminer-aesb.obj `if test -f 'crypto/aesb.c'; then $(CYGPATH_W) 'crypto/aesb.c'; else $(CYGPATH_W) '$(srcdir)/crypto/aesb.c'; fi`
	$(AM_V_at)$(am__mv) crypto/$(DEPDIR)/cpuminer-aesb.Tpo crypto/$(DEPDIR)/cpuminer-aesb.Po
#	$(AM_V_CC)source='crypto/aesb.c' object='crypto/cpuminer-aesb.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o crypto/cpuminer-aesb.obj `if test -f 'crypto/aesb.c'; then $(CYGPATH_W) 'crypto/aesb.c'; else $(CYGPATH_W) '$(srcdir)/crypto/aesb.c'; fi`

algo/blake/cpuminer-blake.o: algo/blake/blake.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/blake/cpuminer-blake.o -MD -MP -MF algo/blake/$(DEPDIR)/cpuminer-blake.Tpo -c -o algo/blake/cpuminer-blake.o `test -f 'algo/blake/blake.c' || echo '$(srcdir)/'`algo/blake/blake.c
	$(AM_V_at)$(am__mv) algo/blake/$(DEPDIR)/cpuminer-blake.Tpo algo/blake/$(DEPDIR)/cpuminer-blake.Po
#	$(AM_V_CC)source='algo/blake/blake.c' object='algo/blake/cpuminer-blake.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/blake/cpuminer-blake.o `test -f 'algo/blake/blake.c' || echo '$(srcdir)/'`algo/blake/blake.c

algo/blake/cpuminer-blake.obj: algo/blake/blake.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/blake/cpuminer-blake.obj -MD -MP -MF algo/blake/$(DEPDIR)/cpuminer-blake.Tpo -c -o algo/blake/cpuminer-blake.obj `if test -f 'algo/blake/blake.c'; then $(CYGPATH_W) 'algo/blake/blake.c'; else $(CYGPATH_W) '$(srcdir)/algo/blake/blake.c'; fi`
	$(AM_V_at)$(am__mv) algo/blake/$(DEPDIR)/cpuminer-blake.Tpo algo/blake/$(DEPDIR)/cpuminer-blake.Po
#	$(AM_V_CC)source='algo/blake/blake.c' object='algo/blake/cpuminer-blake.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/blake/cpuminer-blake.obj `if test -f 'algo/blake/blake.c'; then $(CYGPATH_W) 'algo/blake/blake.c'; else $(CYGPATH_W) '$(srcdir)/algo/blake/blake.c'; fi`

algo/blake/cpuminer-blake2.o: algo/blake/blake2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/blake/cpuminer-blake2.o -MD -MP -MF algo/blake/$(DEPDIR)/cpuminer-blake2.Tpo -c -o algo/blake/cpuminer-blake2.o `test -f 'algo/blake/blake2.c' || echo '$(srcdir)/'`algo/blake/blake2.c
	$(AM_V_at)$(am__mv) algo/blake/$(DEPDIR)/cpuminer-blake2.Tpo algo/blake/$(DEPDIR)/cpuminer-blake2.Po
#	$(AM_V_CC)source='algo/blake/blake2.c' object='algo/blake/cpuminer-blake2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/blake/cpuminer-blake2.o `test -f 'algo/blake/blake2.c' || echo '$(srcdir)/'`algo/blake/blake2.c

algo/blake/cpuminer-blake2.obj: algo/blake/blake2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/blake/cpuminer-blake2.obj -MD -MP -MF algo/blake/$(DEPDIR)/cpuminer-blake2.Tpo -c -o algo/blake/cpuminer-blake2.obj `if test -f 'algo/blake/blake2.c'; then $(CYGPATH_W) 'algo/blake/blake2.c'; else $(CYGPATH_W) '$(srcdir)/algo/blake/blake2.c'; fi`
	$(AM_V_at)$(am__mv) algo/blake/$(DEPDIR)/cpuminer-blake2.Tpo algo/blake/$(DEPDIR)/cpuminer-blake2.Po
#	$(AM_V_CC)source='algo/blake/blake2.c' object='algo/blake/cpuminer-blake2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/blake/cpuminer-blake2.obj `if test -f 'algo/blake/blake2.c'; then $(CYGPATH_W) 'algo/blake/blake2.c'; else $(CYGPATH_W) '$(srcdir)/algo/blake/blake2.c'; fi`

algo/lyra2/cpuminer-lyra2.o: algo/lyra2/lyra2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/lyra2/cpuminer-lyra2.o -MD -MP -MF algo/lyra2/$(DEPDIR)/cpuminer-lyra2.Tpo -c -o algo/lyra2/cpuminer-lyra2.o `test -f 'algo/lyra2/lyra2.c' || echo '$(srcdir)/'`algo/lyra2/lyra2.c
	$(AM_V_at)$(am__mv) algo/lyra2/$(DEPDIR)/cpuminer-lyra2.Tpo algo/lyra2/$(DEPDIR)/cpuminer-lyra2.Po
#	$(AM_V_CC)source='algo/lyra2/lyra2.c' object='algo/lyra2/cpuminer-lyra2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/lyra2/cpuminer-lyra2.o `test -f 'algo/lyra2/lyra2.c' || echo '$(srcdir)/'`algo/lyra2/lyra2.c

algo/lyra2/cpuminer-lyra2.obj: algo/lyra2/lyra2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/lyra2/cpuminer-lyra2.obj -MD -MP -MF algo/lyra2/$(DEPDIR)/cpuminer-lyra2.Tpo -c -o algo/lyra2/cpuminer-lyra2.obj `if test -f 'algo/lyra2/lyra2.c'; then $(CYGPATH_W) 'algo/lyra2/lyra2.c'; else $(CYGPATH_W) '$(srcdir)/algo/lyra2/lyra2.c'; fi`
	$(AM_V_at)$(am__mv) algo/lyra2/$(DEPDIR)/cpuminer-lyra2.Tpo algo/lyra2/$(DEPDIR)/cpuminer-lyra2.Po
#	$(AM_V_CC)source='algo/lyra2/lyra2.c' object='algo/lyra2/cpuminer-lyra2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/lyra2/cpuminer-lyra2.obj `if test -f 'algo/lyra2/lyra2.c'; then $(CYGPATH_W) 'algo/lyra2/lyra2.c'; else $(CYGPATH_W) '$(srcdir)/algo/lyra2/lyra2.c'; fi`

algo/lyra2/cpuminer-sponge.o: algo/lyra2/sponge.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/lyra2/cpuminer-sponge.o -MD -MP -MF algo/lyra2/$(DEPDIR)/cpuminer-sponge.Tpo -c -o algo/lyra2/cpuminer-sponge.o `test -f 'algo/lyra2/sponge.c' || echo '$(srcdir)/'`algo/lyra2/sponge.c
	$(AM_V_at)$(am__mv) algo/lyra2/$(DEPDIR)/cpuminer-sponge.Tpo algo/lyra2/$(DEPDIR)/cpuminer-sponge.Po
#	$(AM_V_CC)source='algo/lyra2/sponge.c' object='algo/lyra2/cpuminer-sponge.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/lyra2/cpuminer-sponge.o `test -f 'algo/lyra2/sponge.c' || echo '$(srcdir)/'`algo/lyra2/sponge.c

algo/lyra2/cpuminer-sponge.obj: algo/lyra2/sponge.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/lyra2/cpuminer-sponge.obj -MD -MP -MF algo/lyra2/$(DEPDIR)/cpuminer-sponge.Tpo -c -o algo/lyra2/cpuminer-sponge.obj `if test -f 'algo/lyra2/sponge.c'; then $(CYGPATH_W) 'algo/lyra2/sponge.c'; else $(CYGPATH_W) '$(srcdir)/algo/lyra2/sponge.c'; fi`
	$(AM_V_at)$(am__mv) algo/lyra2/$(DEPDIR)/cpuminer-sponge.Tpo algo/lyra2/$(DEPDIR)/cpuminer-sponge.Po
#	$(AM_V_CC)source='algo/lyra2/sponge.c' object='algo/lyra2/cpuminer-sponge.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/lyra2/cpuminer-sponge.obj `if test -f 'algo/lyra2/sponge.c'; then $(CYGPATH_W) 'algo/lyra2/sponge.c'; else $(CYGPATH_W) '$(srcdir)/algo/lyra2/sponge.c'; fi`

algo/lyra2/cpuminer-zcoin.o: algo/lyra2/zcoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/lyra2/cpuminer-zcoin.o -MD -MP -MF algo/lyra2/$(DEPDIR)/cpuminer-zcoin.Tpo -c -o algo/lyra2/cpuminer-zcoin.o `test -f 'algo/lyra2/zcoin.c' || echo '$(srcdir)/'`algo/lyra2/zcoin.c
	$(AM_V_at)$(am__mv) algo/lyra2/$(DEPDIR)/cpuminer-zcoin.Tpo algo/lyra2/$(DEPDIR)/cpuminer-zcoin.Po
#	$(AM_V_CC)source='algo/lyra2/zcoin.c' object='algo/lyra2/cpuminer-zcoin.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/lyra2/cpuminer-zcoin.o `test -f 'algo/lyra2/zcoin.c' || echo '$(srcdir)/'`algo/lyra2/zcoin.c

algo/lyra2/cpuminer-zcoin.obj: algo/lyra2/zcoin.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/lyra2/cpuminer-zcoin.obj -MD -MP -MF algo/lyra2/$(DEPDIR)/cpuminer-zcoin.Tpo -c -o algo/lyra2/cpuminer-zcoin.obj `if test -f 'algo/lyra2/zcoin.c'; then $(CYGPATH_W) 'algo/lyra2/zcoin.c'; else $(CYGPATH_W) '$(srcdir)/algo/lyra2/zcoin.c'; fi`
	$(AM_V_at)$(am__mv) algo/lyra2/$(DEPDIR)/cpuminer-zcoin.Tpo algo/lyra2/$(DEPDIR)/cpuminer-zcoin.Po
#	$(AM_V_CC)source='algo/lyra2/zcoin.c' object='algo/lyra2/cpuminer-zcoin.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/lyra2/cpuminer-zcoin.obj `if test -f 'algo/lyra2/zcoin.c'; then $(CYGPATH_W) 'algo/lyra2/zcoin.c'; else $(CYGPATH_W) '$(srcdir)/algo/lyra2/zcoin.c'; fi`

algo/sha2/cpuminer-sha2.o: algo/sha2/sha2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/sha2/cpuminer-sha2.o -MD -MP -MF algo/sha2/$(DEPDIR)/cpuminer-sha2.Tpo -c -o algo/sha2/cpuminer-sha2.o `test -f 'algo/sha2/sha2.c' || echo '$(srcdir)/'`algo/sha2/sha2.c
	$(AM_V_at)$(am__mv) algo/sha2/$(DEPDIR)/cpuminer-sha2.Tpo algo/sha2/$(DEPDIR)/cpuminer-sha2.Po
#	$(AM_V_CC)source='algo/sha2/sha2.c' object='algo/sha2/cpuminer-sha2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/sha2/cpuminer-sha2.o `test -f 'algo/sha2/sha2.c' || echo '$(srcdir)/'`algo/sha2/sha2.c

algo/sha2/cpuminer-sha2.obj: algo/sha2/sha2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT algo/sha2/cpuminer-sha2.obj -MD -MP -MF algo/sha2/$(DEPDIR)/cpuminer-sha2.Tpo -c -o algo/sha2/cpuminer-sha2.obj `if test -f 'algo/sha2/sha2.c'; then $(CYGPATH_W) 'algo/sha2/sha2.c'; else $(CYGPATH_W) '$(srcdir)/algo/sha2/sha2.c'; fi`
	$(AM_V_at)$(am__mv) algo/sha2/$(DEPDIR)/cpuminer-sha2.Tpo algo/sha2/$(DEPDIR)/cpuminer-sha2.Po
#	$(AM_V_CC)source='algo/sha2/sha2.c' object='algo/sha2/cpuminer-sha2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o algo/sha2/cpuminer-sha2.obj `if test -f 'algo/sha2/sha2.c'; then $(CYGPATH_W) 'algo/sha2/sha2.c'; else $(CYGPATH_W) '$(srcdir)/algo/sha2/sha2.c'; fi`

compat/cpuminer-winansi.o: compat/winansi.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT compat/cpuminer-winansi.o -MD -MP -MF compat/$(DEPDIR)/cpuminer-winansi.Tpo -c -o compat/cpuminer-winansi.o `test -f 'compat/winansi.c' || echo '$(srcdir)/'`compat/winansi.c
	$(AM_V_at)$(am__mv) compat/$(DEPDIR)/cpuminer-winansi.Tpo compat/$(DEPDIR)/cpuminer-winansi.Po
#	$(AM_V_CC)source='compat/winansi.c' object='compat/cpuminer-winansi.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o compat/cpuminer-winansi.o `test -f 'compat/winansi.c' || echo '$(srcdir)/'`compat/winansi.c

compat/cpuminer-winansi.obj: compat/winansi.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -MT compat/cpuminer-winansi.obj -MD -MP -MF compat/$(DEPDIR)/cpuminer-winansi.Tpo -c -o compat/cpuminer-winansi.obj `if test -f 'compat/winansi.c'; then $(CYGPATH_W) 'compat/winansi.c'; else $(CYGPATH_W) '$(srcdir)/compat/winansi.c'; fi`
	$(AM_V_at)$(am__mv) compat/$(DEPDIR)/cpuminer-winansi.Tpo compat/$(DEPDIR)/cpuminer-winansi.Po
#	$(AM_V_CC)source='compat/winansi.c' object='compat/cpuminer-winansi.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(cpuminer_CFLAGS) $(CFLAGS) -c -o compat/cpuminer-winansi.obj `if test -f 'compat/winansi.c'; then $(CYGPATH_W) 'compat/winansi.c'; else $(CYGPATH_W) '$(srcdir)/compat/winansi.c'; fi`

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

cpuminer-uint256.o: uint256.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT cpuminer-uint256.o -MD -MP -MF $(DEPDIR)/cpuminer-uint256.Tpo -c -o cpuminer-uint256.o `test -f 'uint256.cpp' || echo '$(srcdir)/'`uint256.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/cpuminer-uint256.Tpo $(DEPDIR)/cpuminer-uint256.Po
#	$(AM_V_CXX)source='uint256.cpp' object='cpuminer-uint256.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o cpuminer-uint256.o `test -f 'uint256.cpp' || echo '$(srcdir)/'`uint256.cpp

cpuminer-uint256.obj: uint256.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT cpuminer-uint256.obj -MD -MP -MF $(DEPDIR)/cpuminer-uint256.Tpo -c -o cpuminer-uint256.obj `if test -f 'uint256.cpp'; then $(CYGPATH_W) 'uint256.cpp'; else $(CYGPATH_W) '$(srcdir)/uint256.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/cpuminer-uint256.Tpo $(DEPDIR)/cpuminer-uint256.Po
#	$(AM_V_CXX)source='uint256.cpp' object='cpuminer-uint256.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o cpuminer-uint256.obj `if test -f 'uint256.cpp'; then $(CYGPATH_W) 'uint256.cpp'; else $(CYGPATH_W) '$(srcdir)/uint256.cpp'; fi`
install-man1: $(dist_man_MANS)
	@$(NORMAL_INSTALL)
	@list1=''; \
	list2='$(dist_man_MANS)'; \
	test -n "$(man1dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man1dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man1dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.1[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
	done; }

uninstall-man1:
	@$(NORMAL_UNINSTALL)
	@list=''; test -n "$(man1dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	l2='$(dist_man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.1[a-z]*$$/p'; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	dir='$(DESTDIR)$(man1dir)'; $(am__uninstall_files_from_dir)

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(PROGRAMS) $(MANS) cpuminer-config.h
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f algo/blake/$(DEPDIR)/$(am__dirstamp)
	-rm -f algo/blake/$(am__dirstamp)
	-rm -f algo/lyra2/$(DEPDIR)/$(am__dirstamp)
	-rm -f algo/lyra2/$(am__dirstamp)
	-rm -f algo/sha2/$(DEPDIR)/$(am__dirstamp)
	-rm -f algo/sha2/$(am__dirstamp)
	-rm -f algo/sha3/$(DEPDIR)/$(am__dirstamp)
	-rm -f algo/sha3/$(am__dirstamp)
	-rm -f asm/$(DEPDIR)/$(am__dirstamp)
	-rm -f asm/$(am__dirstamp)
	-rm -f compat/$(DEPDIR)/$(am__dirstamp)
	-rm -f compat/$(am__dirstamp)
	-rm -f crypto/$(DEPDIR)/$(am__dirstamp)
	-rm -f crypto/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR) algo/blake/$(DEPDIR) algo/lyra2/$(DEPDIR) algo/sha2/$(DEPDIR) algo/sha3/$(DEPDIR) asm/$(DEPDIR) compat/$(DEPDIR) crypto/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-man

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man: install-man1

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR) algo/blake/$(DEPDIR) algo/lyra2/$(DEPDIR) algo/sha2/$(DEPDIR) algo/sha3/$(DEPDIR) asm/$(DEPDIR) compat/$(DEPDIR) crypto/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-man

uninstall-man: uninstall-man1

.MAKE: $(am__recursive_targets) all install-am install-strip

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--refresh check check-am clean clean-binPROGRAMS \
	clean-cscope clean-generic cscope cscopelist-am ctags ctags-am \
	dist dist-all dist-bzip2 dist-gzip dist-lzip dist-shar \
	dist-tarZ dist-xz dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-hdr \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-man1 install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS uninstall-man \
	uninstall-man1

.PRECIOUS: Makefile


# special CFLAGS (if you find a simpler way to do that tell me ;)
#cpuminer-neoscrypt.o: neoscrypt.c
#	@echo "CUSTOM ${@}: ${filter %.o,${^}} ${filter %.c,${^}}"
#	$(CC) $(common_ccflags) -g -O3 $(gprof_cflags) -MT $@ -MD -MP -c -o $@ $<

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
